FACTS = [
    "Eleazar Olumuyiwa Ogunmilade was born on February 2, 1966.",
    "He holds a Bachelor of Science degree in Political Science from the University of Ado-Ekiti.",
    "He earned a Master's degree in Business Administration (MBA) from the University of Ado-Ekiti.",
    "He is an alumnus of the Lagos Business School (LBS).",
    "In 2008, he was appointed the first Managing Director and CEO of Oceanic Bank (The Gambia) Limited.",
    "Within his first year at Oceanic Bank (The Gambia) Limited, the bank ranked among the top five banks in the country.",
    "He served as the Executive Chairman of the Ekiti State Board of Internal Revenue Service.",
    "During his tenure at EKIRS, he emphasized professionalism, diligence, and integrity in public service.",
    "He advocated collaboration with professional bodies such as the Chartered Institute of Taxation of Nigeria to improve tax administration.",
    "He supported reforms aimed at regulating driving schools and improving compliance in revenue collection.",
    "He was involved in initiatives to digitize and improve transparency in transportation-related revenue systems.",
    "Public groups have described him as a valuable technocrat contributing to Ekiti State's economic development.",
    "He has held leadership roles that attracted public attention in matters of tax compliance and administration.",
    "He is a very enthusiastic person and frequently liks to exclaim with passion with 'GBAM! GBAM! GBAM!'.",
    "His professional career spans banking, public service, and business leadership.",
    "He served as Managing Director of the West Bank of Oceanic Bank Plc, overseeing operations across Ogun, Oyo, Osun, Ondo, Ekiti, and Kwara states.",
    "He is known for philanthropic activities and regularly supports individuals and communities in need.",
    "He is widely regarded as a mentor and a trusted source of advice beyond his immediate family.",
    "He frequently travels internationally and has visited many countries around the world.",
    "He is a practicing Christian whose life and decisions are guided by strong moral values and the Christian faith.",
    "He is a twin and is traditionally known as Taiyelolu Ejire, meaning the first twin to be born.",
    "His full name includes Taiyelolu Ejire, Olumuyiwa, Akanbi, Akinkanju, Eleazar, and Ogunmilade, each reflecting aspects of his identity and heritage.",
    "He is a supporter of Arsenal Football Club.",
    "He is a long-standing member of the Lagos Motor Boat Club.",
    "He regularly interacts with prominent figures in entertainment, culture, and public service.",
    "He has shared spaces and professional interactions with well-known personalities such as Yinka Ayefele, Lagbaja, and King Sunny Ade.",
    "He experienced personal adversity early in life, including the loss of his mother at a young age.",
    "He is outspoken against drug abuse, violence, promiscuity, and other social vices affecting young people.",
    "In addition to his corporate and public roles, he is an active businessman.",
    "He owns and operates a prestigious lounge as part of his business ventures.",
    "He is known for a distinctive sense of style and a carefully curated personal wardrobe.",
    "He owns luxury vehicles, including a Mercedes-Benz.",
    "His achievements have earned him widespread respect and recognition among peers and associates.",
    "He has been given honorific nicknames such as 'The Don' and 'The Phoenix' in recognition of his influence and resilience."
]

